server:
  port: 9021

spring:
  cloud:
    config:
      enabled: false
  
  datasource:
   driver-class-name: oracle.jdbc.OracleDriver
   url: jdbc:oracle:thin:@localhost:1521:xe
   username: PruebaWeb
   password: PruebaWeb




