server:
  port: 9024

#url -> registry_service, ahí está
eureka:
 client:
  serviceUrl:
   defaultZone: http://localhost:9020/eureka/

spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: products-service
          uri: http://localhost:9022
          predicates:
             #Va a buscar en /productos/** si hay algun controlador que maneje estas solicitudes, es decir
             #todas las llamadas que vengan con /productos las va a redireccionar aqui
            - Path=/productos/**
        - id: user-service
          uri: http://localhost:9021
          predicates:
            - Path=/usuarios/** 