server:
  port: 9022

spring:  
  datasource:
   driver-class-name: oracle.jdbc.OracleDriver
   url: jdbc:oracle:thin:@localhost:1521:xe
   username: PruebaWeb
   password: PruebaWeb

#url -> registry_service, ahí está
eureka:
 client:
  serviceUrl:
   defaultZone: http://localhost:9020/eureka/

spring:
	cloud:
		openfeign:
			client:
				config:
					feignName:
      url: http://localhost:9021
						connectTimeout: 5000
						readTimeout: 5000

