server:
  port: 9022

spring:  
  datasource:
   driver-class-name: oracle.jdbc.OracleDriver
   url: jdbc:oracle:thin:@localhost:1521:xe
   username: PruebaWeb
   password: PruebaWeb

#url -> registry_service, ahí está
eureka:
 client:
  serviceUrl:
   defaultZone: http://localhost:9020/eureka/

Feign:
 hystrix:
  enabled: true